/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.hw01;

import java.util.Set;

import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Sets;

public class HelloOtus {

    /**
     * Prints all possible combinations of fruits
     *
     * @param args not used
     */
    public static void main(String[] args) {
        //
        // define set of fruits
        Set<String> fruits = 
            ImmutableSet.<String>builder()
            .add("apple")
            .add("orange")
            .add("banana")
            .add("guava")
            .build();

        // all combinations
        Set<Set<String>> fruitsPowerSet = Sets.powerSet(fruits);

        // print combinations
        for (Set<String> fruit : fruitsPowerSet) {
            System.out.println(fruit);
        }
    }

}
